services:
  local-db:
    image: postgres:15.5-alpine
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_DB=demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'